131 add adaptive layout
NotarizedScreenshot/notaryshot-frontend pull request #135
Opened 2023-06-29 20:06 UTC by poludnev

2023-07-29 11:26 UTC, utgarda approved these changes
Pls take care of the nits,
invite another pair of eyes to see all the scss,
 and merge!

2023-07-29 11:26 UTC, utgarda commented on src/components/TweetResults/components/NotarizeButton/NotarizeButton.tsx
> +    updateStateOnTransaction('Waiting for transaction...');
https://www.figma.com/file/E9Fe71isrR7uFiFdt3Yw7b/Finity-Design-System-%F0%9F%92%9C-(Community)?type=design&node-id=1537-43950&mode=design&t=qttRyNX7qMCeD4DW-0


![image](https://github.com/NotarizedScreenshot/notaryshot-frontend/assets/15115/2faec630-1b65-4e4e-84a5-29d204bb03e2)

Pending transaction

2023-07-29 11:26 UTC, utgarda commented on src/components/TweetResults/components/NotarizeButton/NotarizeButton.tsx
> +      setTimeout(() => dispatch(hideModal), 3000);
A constant or an .env entry will be handy for timeouts

2023-07-29 11:26 UTC, utgarda commented on src/components/TweetResults/components/TweetStats/TweetStats.tsx
> +  console.log(favorite_count, quote_count, retweet_count, views_count, bookmark_count);
.

2023-07-29 11:26 UTC, utgarda commented on src/contexts/ContractContext.tsx
> +      args.tokenId.toString();
.

2023-07-29 11:26 UTC, utgarda commented on src/contexts/ContractContext.tsx
> +  const { address } = useAccount();
Can we rename this to `userAddress` here? So many `address` words all around

2023-07-29 11:26 UTC, utgarda commented on src/index.tsx
> +  projectId: '6c1f221e5a67ca1b6d9ecc2ec3303b18',
Move projectId to build variables

2023-07-29 11:26 UTC, utgarda commented on src/lib/apiClient.ts
> +): Promise<{ status: 'failed' | 'success'; transactionHash?: string | null; error?: string | null }> => {
`transactionHash?: string | null;` 
` error?: string | null`
seems a bit messy

2023-08-01 09:39 UTC, habdevs requested changes
I was mostly guided by rem recommendations based on past experience, so maybe my rem was exposed erroneously as not everywhere there is a need for it.

2023-08-08 14:40 UTC, poludnev commented on src/components/Benefits/Benefits.module.scss
> +    @media screen and (max-width: 1023px) {
Why should we? What advantages does it give to us? 

I'm not sure about the behavior of that query on a "print" type device so use it implicitly for the "screen".

2023-08-08 14:44 UTC, poludnev commented on src/components/Header/Header.module.scss
> +          border-radius: 100px;
rem or em are useless for such kind of styles as radius, when you want border be rounded.

2023-08-08 15:10 UTC, merged