add stamped screenshot preview
NotarizedScreenshot/notaryshot-frontend pull request #79
Opened 2023-02-20 21:14 UTC by poludnev

2023-02-23 18:37 UTC, utgarda requested changes
Please take care of the cosmetic issues and 

manage to run the tests in Github Actions
https://github.com/rainbow-me/rainbowkit/issues/461
@Elizavetta please help with the above

2023-02-23 18:37 UTC, utgarda commented on src/App.tsx
> +          ctx.font = '5px monospace';
Can this be a top-level constant or a config value?

2023-02-23 18:37 UTC, utgarda commented on src/App.tsx
> +            if (stringWidth > 480) {
magic number

2023-02-23 18:37 UTC, utgarda commented on src/utils/index.ts
> +  // const url = new URL(sourceUrl);
.

2023-02-23 18:37 UTC, utgarda commented on src/utils/index.ts
> +    'accept-ch':
Please add a comment explaining how and this bogus metadata never gets to the final result.

2023-02-23 18:37 UTC, utgarda commented on src/utils/index.ts
> +export const getOffset = (
Please add usage contract - say that equal sizes aren't supposed to be passed as args.

2023-02-23 18:37 UTC, utgarda commented on src/utils/index.ts
> +    throw new Error('cannot offset if equal sizes');
[typescript assert](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions)

2023-02-23 18:37 UTC, utgarda commented on src/utils/index.ts
> +    throw new Error('offsetRaion more than 1');
.

2023-02-28 12:54 UTC, Elizavetta approved these changes
tests are running; minor improvements done;

2023-02-28 13:26 UTC, merged